// Generated by CoffeeScript 1.11.1

/*
standard compare function, attached as property to prevent passing it around
all the time.
 */

(function() {
  var defaultComparator, order;

  defaultComparator = function(a, b) {
    if (a < b) {
      return -1;
    }
    if (a > b) {
      return 1;
    }
    return 0;
  };


  /*
  exported order function: returns a permutation which rearranges input array
  Parameters:
  @arr: input array
  @compareFunction: optional comparator function, standard is to sort elements
  in increasing order
   */

  order = function(inputArr, compareFunction) {
    var arr, i, ref, results;
    if (typeof compareFunction !== "function") {
      compareFunction = defaultComparator;
    }
    arr = (function() {
      results = [];
      for (var i = 0, ref = inputArr.length; 0 <= ref ? i < ref : i > ref; 0 <= ref ? i++ : i--){ results.push(i); }
      return results;
    }).apply(this);
    return arr.sort(function(a, b) {
      return compareFunction(inputArr[a], inputArr[b]);
    });
  };

  module.exports = order;

}).call(this);
