// Generated by CoffeeScript 1.9.0

/*
merge: combine the two input arrays @left and @right and return
newly created result array containing all their elements in sorted order
 */

(function() {
  var defaultComparator, exports, merge, mergeSort, order;

  merge = function(left, right) {
    var li, result, ri;
    result = [];
    li = 0;
    ri = 0;
    while (li < left.length && ri < right.length) {
      if (merge.comparator(left[li].data, right[ri].data) < 0) {
        result.push(left[li++]);
      } else {
        result.push(right[ri++]);
      }
    }
    return result.concat(left.slice(li)).concat(right.slice(ri));
  };


  /*
  standard compare function, attached as property to prevent passing it around
  all the time.
   */

  defaultComparator = function(a, b) {
    if (a < b) {
      return -1;
    }
    if (a > b) {
      return 1;
    }
    return 0;
  };

  merge.comparator = defaultComparator;


  /*
  mergeSort: main merge sort function which splits arrays into one-element
  arrays and recursively merges them.
   */

  mergeSort = function(items) {
    var left, middle, right;
    if (items.length < 2) {
      return items;
    }
    middle = Math.floor(items.length / 2);
    left = items.slice(0, middle);
    right = items.slice(middle);
    return merge(mergeSort(left), mergeSort(right));
  };


  /*
  exported order function: returns a permutation which rearranges input array
  Parameters:
  @arr: input array
  @compareFunction: optional comparator function, standard is to sort elements
  in increasing order
   */

  order = function(inputArr, compareFunction) {
    var arr;
    if (typeof compareFunction === "function") {
      merge.comparator = compareFunction;
    }
    arr = [];
    arr = inputArr.map(function(e, i) {
      var o;
      o = {};
      o.data = Object(e);
      o.index = i;
      return o;
    });
    arr = mergeSort(arr);
    merge.comparator = defaultComparator;
    return arr.map(function(e) {
      return e.index;
    });
  };

  module.exports = exports = order;

}).call(this);
