// Generated by CoffeeScript 1.9.0
(function() {
  var exports, merge, mergeSort, order;

  merge = function(left, right) {
    var li, result, ri;
    result = [];
    li = 0;
    ri = 0;
    while (li < left.length && ri < right.length) {
      if (merge.comparator(left[li], right[ri]) < 0) {
        result.push(left[li++]);
      } else {
        result.push(right[ri++]);
      }
    }
    return result.concat(left.slice(li)).concat(right.slice(ri));
  };

  merge.comparator = function(a, b) {
    if (a < b) {
      return -1;
    }
    if (a > b) {
      return 1;
    }
    return 0;
  };

  mergeSort = function(items) {
    var left, middle, right;
    if (items.length < 2) {
      return items;
    }
    middle = Math.floor(items.length / 2);
    left = items.slice(0, middle);
    right = items.slice(middle);
    return merge(mergeSort(left), mergeSort(right));
  };

  order = function(arr, compareFunction) {
    if (typeof compareFunction === "function") {
      merge.comparator = compareFunction;
    }
    arr = arr.map(function(e, i) {
      e = Object(e);
      e.index = i;
      return e;
    });
    arr = mergeSort(arr);
    return arr.map(function(e) {
      return e.index;
    });
  };

  module.exports = exports = order;

}).call(this);
